apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-world-service-deployment
spec:
  selector:
    matchLabels:
      app: covid-world-service
  replicas: 1
  template:
    metadata:
      labels:
        app: covid-world-service
    spec:
      containers:
        - name: covid-world-service
          image: waterfox83/covid-world-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
---
# The service (LoadBalancer type) which can be used to access the above running container.
# To create static IP: gcloud compute addresses create helloweb-ip --region us-central1
apiVersion: v1
kind: Service
metadata:
  name: covid-world-service-svc
  labels:
    app: covid-world-service
spec:
  loadBalancerIP: 35.223.189.33
  type: LoadBalancer
  selector:
    app: covid-world-service
  ports:
    - nodePort: 30003
      port: 8080
      name: http-worldport
      targetPort: 8080
